# application.yml
spring:
  datasource:
    url: jdbc:mysql://rm-wz928xp9bdf1q8wrv4o.mysql.rds.aliyuncs.com:3306/daxiong?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: fengyang
    password: Fy3533263
    schema: classpath:schema.sql
---
spring:
    profiles: container
    datasource:
      url: jdbc:mysql://rm-wz928xp9bdf1q8wrv4o.mysql.rds.aliyuncs.com:3306/daxiong?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      username: fengyang
      password: Fy3533263
      schema: classpath:schema.sql
      initialize: true